### ISSUE TITLE
Error with 'Start development version'

### ISSUE THREAD

**Issue by dancesWithCycles** [stadtnavi/digitransit-ui#754]
Hi folks,
Thank you so much for this awesome repository. I am following the [Installation](https://github.com/Stefan-Begerad/digitransit-ui/blob/next/docs/Installation.md) instructions. The instruction ```CONFIG=huejavbn yarn run dev``` comes back to me with the following error. I appreciate any hint pointing me in the right direction. Cheers! 

```
CONFIG=huejavbn yarn run dev
[nodemon] 1.18.10
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /home/user/GitHub/Stefan-Begerad/digitransit-ui/server/**/* /home/user/GitHub/Stefan-Begerad/digitransit-ui/app/**/*
[nodemon] starting `node server/server.js`
Warning: React.createFactory() is deprecated and will be removed in a future major release. Consider using JSX or use React.createElement() directly instead.

Writing js
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] starting `node server/server.js`
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
Updated:
 - SummaryPage_Query.graphql.js
 - SummaryPage_WalkBike_Query.graphql.js
 - ItinerarySummaryListContainer_itineraries.graphql.js
 - ItineraryTab_itinerary.graphql.js
 - queryUtils_SummaryPage_moreItins_Query.graphql.js
 - queryUtils_SummaryPage_Query.graphql.js
Unchanged: 130 files
[nodemon] restarting due to changes...
Watching for changes to js/jsx...
Watching for changes to graphql...
[nodemon] restarting due to changes...
[nodemon] starting `node server/server.js`
Warning: React.createFactory() is deprecated and will be removed in a future major release. Consider using JSX or use React.createElement() directly instead.
You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
https://planner.25stunden.de/otp/routers/default/index/graphqlindex/graphql: Not Found
failed to load availableTickets at launch, retrying
Digitransit-ui available on port 8080
You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
[BABEL] Note: The code generator has deoptimised the styling of /home/user/GitHub/Stefan-Begerad/digitransit-ui/digitransit-component/packages/digitransit-component-dialog-modal/lib/index.js as it exceeds the max of 500KB.
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/user/GitHub/Stefan-Begerad/digitransit-ui/node_modules/react-leaflet/node_modules/@babel/runtime/helpers/esm/extends.js
require() of ES modules is not supported.
require() of /home/user/GitHub/Stefan-Begerad/digitransit-ui/node_modules/react-leaflet/node_modules/@babel/runtime/helpers/esm/extends.js from /home/user/GitHub/Stefan-Begerad/digitransit-ui/node_modules/react-leaflet/es/context.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename extends.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/user/GitHub/Stefan-Begerad/digitransit-ui/node_modules/react-leaflet/node_modules/@babel/runtime/helpers/esm/package.json.

    at Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Object.newLoader [as .js] (/home/user/GitHub/Stefan-Begerad/digitransit-ui/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/user/GitHub/Stefan-Begerad/digitransit-ui/node_modules/react-leaflet/es/context.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/home/user/GitHub/Stefan-Begerad/digitransit-ui/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```

**Comment by leonardehrenfried** [comment]
Are you on node 10? It's the only version supported.

Have you installed watchman?

**Comment by dancesWithCycles** [comment]
What a classic! I am sorry for bothering anyone. Yes, my terminal was set to the wrong node version. Everything is fine with node version v10.24.1. Thanks! Cheers!
